[project]
name = "mmai"
version = "0.1.0"
authors = [
    { name = "Titus", email = "tis@cs.unc.edu" }
]
requires-python = ">=3.13"
dependencies = [
    "evaluate>=0.4.3",
    "torch>=2.6.0",
    "torchaudio>=2.6.0",
    "torchvision>=0.21.0",
    "transformers>=4.49.0",
]
